name: Flutter CI

on:
  push:

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' 
        flutter-version: '2.5.2' 

    - name: open seasame
      run: |
        #sudo apt update  
        sudo apt install tor
        sudo npm install -g @treehouses/cli
        sudo treehouses tor add 22
        sudo treehouses tor
        sudo treehouses tor notice now
        sudo treehouses sshkey github adduser dogi
        sudo treehouses sshkey github adduser rjpadilla
        sudo treehouses sshkey github adduser hiroTochigi
        echo "shh only dreams"
        sleep 1800

    - uses: victorbnl/build-signed-apk@main
      with:
        keystore: ${{ secrets.KEYSTORE }}
        keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
        key_alias: ${{ secrets.KEY_ALIAS }}
        key_password: ${{ secrets.KEY_PASSWORD }}

    - run: |
        flutter clean
        flutter pub get
        flutter pub upgrade
    
    - run: flutter build apk --release #--no-sound-null-safety

    #- run: flutter build apk --no-sound-null-safety
    
    - run: |
        cd build/app/outputs/flutter-apk/
        mv app.apk blueshot.apk
        ls -al
  ios:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '2.5.2' # you can also specify exact version of flutter
        
    - run: |
        flutter clean
        flutter pub get
        cd ios
        pod install

        
    - run: flutter build ios --release --no-codesign
