name: Flutter CI

on:
  push:

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' 
        flutter-version: '2.5.2' 

      env:
        KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    #- name: open seasame
    #  run: |
    #    #sudo apt update  
    #    sudo apt install tor
    #    sudo npm install -g @treehouses/cli
    #    sudo treehouses tor add 22
    #    sudo treehouses tor
    #    sudo treehouses tor notice now
    #    sudo treehouses sshkey github adduser dogi
    #    sudo treehouses sshkey github adduser rjpadilla
    #    sudo treehouses sshkey github adduser hiroTochigi
    #    echo "shh only dreams"
    #    sleep 1800

    #- uses: victorbnl/build-signed-apk@main
    #  with:
    #    keystore: ${{ secrets.KEYSTORE }}
    #    keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
    #    key_alias: ${{ secrets.KEY_ALIAS }}
    #    key_password: ${{ secrets.KEY_PASSWORD }}

    - run: echo "/u3+7QAAAAIAAAABAAAAAQAKdHJlZWhvdXNlcwAAAWtOmrFrAAAFAjCCBP4wDgYK /
KwYBBAEqAhEBAQUABIIE6qV/db9+cu/ZHetltgOJfUNuzf6b2/q8NwtRANUtIDt6 /
SOSDan7YmJjOQMwtObw1tt7tCdLcEh67gyqDxwZwQNPeWiU3mKAwJ6T+wbrgW+zi /
iOqTCMYhzloWduswQIuBRncj8QiU4L6CdSJybN+q9Al9SPHVA2f+YqmT1RGor976 /
9tm8o1+Z9lMMd3+ovD4k7A4BbarLhCeyHN99Xg/USH0jbATHu25CKr7Cam7P5nwe /
JLwSgF/eNulrXM08LQyYyHORaHfn8Db0SSgkDLf+VxHWgxKizKXBG/1H0TSy6T4o /
IgXYhBuQaHP4f3WIEG5IiVgygqdVtAGzyvy5hc5uHtHP76i1uz5bIDKFMWHkmWxH /
OR1A69ypDqWRhTSAS3DpvhQvAO8q6SJL014QY/6NK2rw2PIqWwCkxf22DRj/1zzn /
EYQiOW/sW6gB6AMzKcoCSo4jPRQygkX2Fmfnb14pK/r3Qo9q/KAXykXPRy4HI97C /
e7WK9l7Obt+NpWy1kqsM9Z19cfuoLmKEvFnCd+BXe2NuUPbSLwL1FQoHTx++iJKe /
QY5ei4HvQkXC7SDjtR70X89CuCQNaiDOItS3ozP11Rc6eaZh2HivHUBY4bUQc1zV /
k4biVWjdRsJEVri6EKVQe9kZmQ2sRCNTUa9sHDro56mR2XdCPdASkWiEkx4kMIuT /
ArWusLvHRiSd7ac0+AbpsWyHifbGa0tCjEAu6SZqlu0zWcLZzNhie9J9RoQeL7fT /
7OT31sxZDq4e9wEZtGierV8FR3DrHVmI0uauGG47ZukhNKtnDW1geb02izTsD/v/ /
65fj48+bBTIA2dAQ0zQFIppow8A5k9TS0PgUIDtnmRvtESnn2D3mjwTetQgTQ6nU /
aZtVEfIkP50OUnTyQSLeJMyr5+wUtvE8d7QnBbL7gXHB5MBbDhKHSTlI4lzEDBKP /
t+1kxwvgG5iQ6oiZuYqoblLdUJF/QGjCwn0G6S1fXDW+oHe4mZehb8euK686t4Uu /
OH9SsjZL3aU+VV37pNOLB0e1kX7XFeLjzAtbdaBOm10u1NMc/gdSeelGPb/tPTRf /
nBR/ouHAliPlLvfAWleid+y4/wsu5O/upxznaSZ12sWtAczFeMVRNsMiIuQjuqS4 /
18jWC/GCcYVHvW4rh/i+uDGNTSdpUn9X44ZnRhXAYV0Ap6mymDDexjAWd8m/2VXv /
8ly/de135PPSVizGLqJ8R13gD5nMhJjDmk3MrnY9MLcl6XDs0/iL30BdYNlSZgH4 /
EH/Ue6enesnODQuj1UywVIhz1NL/Wrh60PlpTw39/1HbaYzeFfRO1qHKlGjLSqRx /
W2fJpo5+meOfhgTEu7FI7+0bMxq8PAARhJCr/jHfposyU5VARXhNknsfDRKFB+CP /
OHGEgnF+mO6SSJrpkLQDVmMjrO7BkHXiDvfiXnrswSIOhBsj2SKQwidZWnn3oRbk /
eFALXt2WfEBVDRuusJY8CD5WXhb12IamqDNFEoSWJWWigCdVrvIF1vy+fjmSpH0L /
ymKjNHgTta2xeps+//5nXsIFq96gxn+nZLlJtbMqx0I56e5eu7EthC06A8XUoO4x /
/VzwKpiJAvh3eD3vGl5Z+m4iadTeClvDLjRl7tOWNiG88OQWnagSeGeu7Ty0m8Rw /
K2jh+B2Q5WwL48p/xfij5PSEsr/mhaJrMN8AAAABAAVYLjUwOQAAAzEwggMtMIIC /
FaADAgECAgRhrzgGMA0GCSqGSIb3DQEBCwUAMEYxEzARBgNVBAoTCnRyZWVob3Vz /
ZXMxGjAYBgNVBAsTEXRyZWVob3VzZXMgcmVtb3RlMRMwEQYDVQQDEwp0cmVlaG91 /
c2VzMCAXDTE5MDYxMzAyMTEyOVoYDzIwNjkwNTMxMDIxMTI5WjBGMRMwEQYDVQQK /
Ewp0cmVlaG91c2VzMRowGAYDVQQLExF0cmVlaG91c2VzIHJlbW90ZTETMBEGA1UE /
AxMKdHJlZWhvdXNlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJPg /
CnBoKQyv12xxS6cCeAVxNZDhEkn78/uh2y7LarMQ5UAjOjxoVXm+fWxj/GUP/ZBG /
0BoOtaChVfhmeLfPM6QwJAc1C4b/WTMeQfHkMTQOcD8mK7AHkcHdz6EZUXukryLm /
1JjUwJMfXXXC1pRvleIHs/1DuV60xOmCM3rUf4HkIsehVB8sawAAlLMYMa8kxpW1 /
HyFFBCSjuUGTVX1tEJ7r8FIqP7FQC1t9ZSz5lLrbYGBLquC6Jm1JDMwi8iuki8mI /
0Lyifjaxg0w/O4uJQFtHtb2mhS+WgQ7fMGmR+I7XhrueqmFq4ybR11rHSJ4Chu1S /
qd1T7TTAuWv1i1BRnE0CAwEAAaMhMB8wHQYDVR0OBBYEFGShZbmjT0SiD0vT82Vy /
7oqkNkmQMA0GCSqGSIb3DQEBCwUAA4IBAQCD3LjrpkqTlO/h9NZlThaIdCRwhhaX /
U8xZkudqm+m7kSgVdhsBM/ODcsUcGkTpd1R3xRsrX098virVNin1x/TL4WcLuV/j /
Y6Dg0wsvGFDuZXJ4yhIau2DX9/9Vzo1jepPPPm8MxeySTU6OujhprtSf2zxrgC6J /
JbiKNgtbGydYmQdC9Hi2ZvJx2V0encfOi8f6+x1T7wxPFlmhjENk9Ohta7LCs1d8 /
okSDBatf8hXc2enqQsjVwx1QImWJCD/xrENDJM/ZmEbAqM1sN3Ut33aXvwXLs12L /
sZ4SCvb5Bd6weFXsf1C+rHdXyZ8vtqxRrjPQVtATng/5LhB3WfjEdhJLsjgO7dKI /
WrUSAE1f5r1V5RemSFE=" | base64 -d > $GITHUB_WORKSPACE/android/treehouses-remote.jks
    #- run: echo "${{ secrets.KEYSTORE }}" > $GITHUB_WORKSPACE/android/treehouses-remote.jks
    

    #- run: chmod +x ./android/gradlew
    #- run: ./android/gradlew build
    #- run: ./android/gradlew task

    #- run: ./android/gradlew assembleRelease
    #    -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/android/treehouses-remote.jks 
    #    -Pandroid.injected.signing.store.password=${{ secrets.keystore_password }} 
    #    -Pandroid.injected.signing.key.alias=${{ secrets.key_alias }} 
    #    -Pandroid.injected.signing.key.password=${{ secrets.key_password }}

    - run: |
        flutter clean
        flutter pub get
        flutter pub upgrade
    
    - run: flutter build apk --release #--no-sound-null-safety

    #- run: flutter build apk --no-sound-null-safety
    
    - run: |
        cd build/app/outputs/flutter-apk/
        mv app.apk blueshot.apk
        ls -al
  ios:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '2.5.2' # you can also specify exact version of flutter
        
    - run: |
        flutter clean
        flutter pub get
        cd ios
        pod install

        
    - run: flutter build ios --release --no-codesign
