name: Release

on:
  push:

jobs:
  apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --no-shrink #--no-sound-null-safety
    - run: cd build/app/outputs && tree
    - run: |
        cd build/app/outputs/flutter-apk/
        mv app.apk blueshot.apk || true
        mv app.apk.sha1 hashblue.apk.sha1 || true
        mv app-release.apk blue-release.apk || true
        mv app-debug.apk blue-bug.apk || true
        ls -al
        
    - name: Mobile Security Framework
      run: |
        docker pull opensecurity/mobile-security-framework-mobsf
        docker run -itd -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest 
        cd build/app/outputs/flutter-apk/
        ls -al
        wget http://localhost:8000/api_docs
        MOBSF_API_KEY=$(grep 'REST API Key' api_docs)
        MOBSF_API_KEY=${MOBSF_API_KEY:42:64}
        rm api_docs
        HASH=$(md5sum blueshot.apk)
        HASH=${HASH:0:32}
        curl -F "file=@blueshot.apk" http://localhost:8000/api/v1/upload -H "Authorization:$MOBSF_API_KEY"
        curl -X POST --url http://localhost:8000/api/v1/scan --data "scan_type=apk&file_name=remote.apk&hash=$HASH" -H "Authorization:$MOBSF_API_KEY"
        docker ps
        curl -X POST --url http://localhost:8000/api/v1/download_pdf --data "hash=$HASH" -H "Authorization:$MOBSF_API_KEY" --output ${{ steps.build_id.outputs.id }}-security-scan.pdf
        ls -al        
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/app/outputs/flutter-apk/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
  iOS:
    name: Release iOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: brew install tree
    - run: |
        cd /Users/runner/work/flutter-ble-terminal/flutter-ble-terminal/build/ios/iphoneos
        #tree
        #ls -al
        mkdir Payload
        #mv Runner.app Payload/Runner.app
        cp -R Runner.app Payload
        #cp -R Runner.app/iTunesArtwork /Users/runner/work/flutter-ble-terminal/flutter-ble-terminal/build/ios/iphoneos #no iTunes
        #tar -zcvf Payload.ipa Payload #old
        /usr/bin/zip -r Payload.ipa Payload iTunesArtwork #no iTunes
        #rm -rf Payload iTunesArtwork #no iTunes
        tree
        ls -al
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /Users/runner/work/flutter-ble-terminal/flutter-ble-terminal/build/ios/iphoneos/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true